//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KC.Apps.SpyderLib.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources1 {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources1() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KC.Apps.SpyderLib.Properties.Resources1", typeof(Resources1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ConfigError {
            get {
                return ResourceManager.GetString("ConfigError", resourceCulture);
            }
        }
        
        internal static string IO_Write_Error {
            get {
                return ResourceManager.GetString("IO_Write_Error", resourceCulture);
            }
        }
        
        internal static string Permission_Error_Writing_File {
            get {
                return ResourceManager.GetString("Permission_Error_Writing_File", resourceCulture);
            }
        }
        
        internal static string File_Path_Invalid {
            get {
                return ResourceManager.GetString("File_Path_Invalid", resourceCulture);
            }
        }
        
        internal static string Buffer_Block_Data_Error {
            get {
                return ResourceManager.GetString("Buffer_Block_Data_Error", resourceCulture);
            }
        }
        
        internal static string DownloadController_DownloadController_Download_Controller_Initialized_ {
            get {
                return ResourceManager.GetString("DownloadController_DownloadController_Download_Controller_Initialized_", resourceCulture);
            }
        }
        
        internal static string AbstractCacheIndex_GetValueFromWebAsync_Cache_miss__Loading_page_from_web__0_ {
            get {
                return ResourceManager.GetString("AbstractCacheIndex_GetValueFromWebAsync_Cache_miss__Loading_page_from_web__0_", resourceCulture);
            }
        }
    }
}
